version: "3"
services:
  web:
    build:
      context: .
    command: newrelic-admin run-program gunicorn app.main:app --workers=1 --bind 0.0.0.0:5000 --reload
    volumes:
      - ./app:/app
    depends_on:
      - db
    ports:
      - 5005:5000
    environment:
      DATABASE_URL: "postgresql://todolist_app:todolist_app@db:5432/todolist_app"
      LOG_LEVEL: "INFO"
      NEW_RELIC_APP_NAME: "todolist-app"
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: true
    env_file:
      - .env
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=todolist_app
      - POSTGRES_PASSWORD=todolist_app
      - POSTGRES_DB=todolist_app

volumes:
  postgres_data:
    driver: local
